server:
  port: 8080

spring:
  application:
    name: auth-service
  
  threads:
    virtual:
      enabled: true
  
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate # Production grade: use flyway for migrations
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: auth-group
      auto-offset-reset: earliest

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days
    oauth2:
      google:
        client-id: ${GOOGLE_CLIENT_ID:placeholder-id}
        client-secret: ${GOOGLE_CLIENT_SECRET:placeholder-secret}
        redirect-uri: "http://localhost:8080/oauth2/callback/google"
      facebook:
        client-id: ${FACEBOOK_CLIENT_ID:placeholder-id}
        client-secret: ${FACEBOOK_CLIENT_SECRET:placeholder-secret}
        redirect-uri: "http://localhost:8080/oauth2/callback/facebook"
  mail:
    from-email: no-reply@facebook-clone.com
    enabled: true
  frontend-url: "http://localhost:5173"
