apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  # user: minioadmin (base64)
  root-user: bWluaW9hZG1pbg==
  # password: minioadmin (base64)
  root-password: bWluaW9hZG1pbg==
